
language: android
jdk: oraclejdk8
sudo: false

notifications:  #Optional
    email:
        - jed.westover1986@gmail.com #Add your email address

env:
  global:   #Optional
    - ANDROID_TARGET=android-19
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

android:
    components:
        - platform-tools
        - tools
        - build-tools-25.0.0
        - extra-android-m2repository
        - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

script:
    - android list targets
    - ./gradlew build jacocoTestReport assembleAndroidTest
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - ./gradlew connectedCheck
after_success:
    - bash <(curl -s https://codecov.io/bash)